services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: deginmulbah/edubridge-tracker
    ports:
      - "3000:3000"
    env_file:
      - .env
    # volumes:
    #   - .:/app
    #   - /app/node_modules