name: CI/CD with Docker Hub and VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/edubridge-tracker
          docker build -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p ${{ secrets.VPS_PORT || 22 }} ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy on VPS
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} -p ${{ secrets.VPS_PORT || 22 }} << 'EOF'
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/edubridge-tracker
           
            docker run -d -p 3000:3000 \
              -e PG_CONNECTION_STRING = ${{ secrets.PG_CONNECTION_STRING }} \
              -e COOKIE_SECRET = ${{ secrets.COOKIE_SECRET }} \
              -e COOKIE_NAME = ${{ secrets.COOKIE_NAME}} \
              -e COOKIE_SECURED = ${{ secrets.COOKIE_SECURED }} \
              -e RATE_LIMIT_MAX = ${{ secrets.RATE_LIMIT_MAX }} \
              -e NODE_ENV=production \
            ${{ secrets.DOCKERHUB_USERNAME }}/edubridge-tracker:latest
          EOF