name: CI/CD with Docker Hub and VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tag: ${{ secrets.DOCKERHUB_USERNAME }}/edubridge-tracker:latest

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p ${{ secrets.VPS_PORT || 22 }} ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy on VPS
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} -p ${{ secrets.VPS_PORT || 22 }} << 'EOF'
          docker compose pull
          docker compose up -d
        env:
          NODE_ENV: production
          PG_CONNECTION_STRING: ${{ secrets.PG_CONNECTION_STRING }}
          COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
          COOKIE_SECURED: ${{ secrets.COOKIE_SECURED }}
          RATE_LIMIT_MAX: ${{ secrets.RATE_LIMIT_MAX }}
